# Generated by Django 5.0.3 on 2024-04-07 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
